# MetalLB Configuration
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: website-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.2.250/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lan-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - website-pool
